### ISSUE TITLE
🛑 長橋證券（新加坡）- zh-HK is down

### ISSUE THREAD

**Issue by huacnlee** [longbridgeapp/uptime#1011]
In [`5dcd599`](https://github.com/longbridgeapp/uptime/commit/5dcd599eb8993906a818a571953547e5573acb50
), 長橋證券（新加坡）- zh-HK (https://longbridge.sg/zh-HK) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by hold-baby** [comment]
证书过期，已通知运维处理

**Comment by hold-baby** [comment]
已恢复
