### ISSUE TITLE
🛑 長橋證券（新西兰）- en is down

### ISSUE THREAD

**Issue by huacnlee** [longbridgeapp/uptime#211]
In [`f94cfce`](https://github.com/longbridgeapp/uptime/commit/f94cfce7af1b17b29dcd4e840cb0d2bbfd24b4a4
), 長橋證券（新西兰）- en (https://longbridge.global/en) was **down**:
- HTTP code: 404
- Response time: 924 ms

**Comment by hold-baby** [comment]
处理中
